---
- name: Add vCenter license (if provided)
  community.vmware.vcenter_license:
    hostname: "{{ infrastructure.vcenter.ip }}"
    username: "administrator@vsphere.local"
    password: "{{ vcenter_password }}"
    license: "{{ infrastructure.vcenter.vcenter_license_key }}"
    state: present
    validate_certs: false
  delegate_to: localhost
  no_log: "{{ not (vmware_debug | default(false) | bool) }}"
  when: infrastructure.vcenter.vcenter_license_key | default('') | length > 0

- name: Add ESXi license to each host (if provided)
  community.vmware.vcenter_license:
    hostname: "{{ infrastructure.vcenter.ip }}"
    username: "administrator@vsphere.local"
    password: "{{ vcenter_password }}"
    license: "{{ infrastructure.vcenter.esxi_license_key }}"
    esxi_hostname: "{{ item.hostname }}"
    state: present
    validate_certs: false
  loop: "{{ infrastructure.esxi | default([]) }}"
  delegate_to: localhost
  no_log: "{{ not (vmware_debug | default(false) | bool) }}"
  when:
    - infrastructure.vcenter.esxi_license_key | default('') | length > 0
    - item.hostname is defined

