terraform {
  required_version = ">= 1.5.0"

  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "~> 2.6"
    }
    time = {
      source  = "hashicorp/time"
      version = "~> 0.11"
    }
  }
}

provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = true
}

variable "vsphere_user" {
  type = string
  validation {
    condition     = length(trimspace(var.vsphere_user)) > 0
    error_message = "vsphere_user must not be empty."
  }
}

variable "vsphere_password" {
  type      = string
  sensitive = true
}

variable "vsphere_server" {
  type = string
  validation {
    condition     = length(trimspace(var.vsphere_server)) > 0
    error_message = "vsphere_server must not be empty."
  }
}

variable "datacenter" {
  type = string
  validation {
    condition     = length(trimspace(var.datacenter)) > 0
    error_message = "datacenter must not be empty."
  }
}

variable "cluster" {
  type = string
  validation {
    condition     = length(trimspace(var.cluster)) > 0
    error_message = "cluster must not be empty."
  }
}

variable "datastore" {
  type = string
  validation {
    condition     = length(trimspace(var.datastore)) > 0
    error_message = "datastore must not be empty."
  }
}

variable "network" {
  type = string
  validation {
    condition     = length(trimspace(var.network)) > 0
    error_message = "network must not be empty."
  }
}

variable "template_name" {
  type        = string
  description = "VM template name for SCOS/FCOS node cloning"
  validation {
    condition     = length(trimspace(var.template_name)) > 0
    error_message = "template_name must not be empty."
  }
}

variable "vm_folder" {
  type        = string
  default     = ""
  description = "Optional vSphere VM folder (empty = root VM folder)"
}

variable "bootstrap_name" {
  type    = string
  default = "bootstrap"
}

variable "bootstrap_mac_address" {
  type        = string
  description = "Static MAC for bootstrap VM"
  default     = "00:50:56:ad:d0:c5"
  validation {
    condition     = can(regex("^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$", var.bootstrap_mac_address))
    error_message = "bootstrap_mac_address must be a valid MAC address (aa:bb:cc:dd:ee:ff)."
  }
}

variable "bootstrap_ignition_b64_file" {
  type        = string
  description = "Path to bootstrap.64 generated by ansible role"
  validation {
    condition     = length(trimspace(var.bootstrap_ignition_b64_file)) > 0
    error_message = "bootstrap_ignition_b64_file must not be empty."
  }
}

variable "master_ignition_b64_file" {
  type        = string
  description = "Path to master.64 generated by ansible role"
  validation {
    condition     = length(trimspace(var.master_ignition_b64_file)) > 0
    error_message = "master_ignition_b64_file must not be empty."
  }
}

variable "worker_ignition_b64_file" {
  type        = string
  description = "Path to worker.64 generated by ansible role"
  validation {
    condition     = length(trimspace(var.worker_ignition_b64_file)) > 0
    error_message = "worker_ignition_b64_file must not be empty."
  }
}

variable "bootstrap_cpu" {
  type    = number
  default = 4
}

variable "bootstrap_memory_mb" {
  type    = number
  default = 16384
}

variable "bootstrap_to_nodes_delay_seconds" {
  type        = number
  description = "Delay after bootstrap VM creation before creating masters/workers"
  default     = 120
  validation {
    condition     = var.bootstrap_to_nodes_delay_seconds >= 0 && var.bootstrap_to_nodes_delay_seconds <= 3600
    error_message = "bootstrap_to_nodes_delay_seconds must be between 0 and 3600."
  }
}

variable "master_cpu" {
  type    = number
  default = 4
}

variable "master_memory_mb" {
  type    = number
  default = 16384
}

variable "worker_cpu" {
  type    = number
  default = 4
}

variable "worker_memory_mb" {
  type    = number
  default = 16384
}

variable "haproxy_enabled" {
  type        = bool
  description = "Whether to create the HAProxy VM"
  default     = false
}

variable "haproxy_name" {
  type        = string
  description = "HAProxy VM name"
  default     = "haproxy"
}

variable "haproxy_mac_address" {
  type        = string
  description = "Static MAC for HAProxy VM"
  default     = "00:50:56:ad:10:15"
  validation {
    condition     = can(regex("^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$", var.haproxy_mac_address))
    error_message = "haproxy_mac_address must be a valid MAC address (aa:bb:cc:dd:ee:ff)."
  }
}

variable "haproxy_cpu" {
  type    = number
  default = 2
}

variable "haproxy_memory_mb" {
  type    = number
  default = 4096
}

variable "masters" {
  type = list(object({
    name        = string
    mac_address = string
  }))
  default = [
    { name = "master01", mac_address = "00:50:56:ad:90:fd" },
    { name = "master02", mac_address = "00:50:56:ad:40:2a" },
    { name = "master03", mac_address = "00:50:56:ad:17:f6" }
  ]
  validation {
    condition     = length(var.masters) > 0 && length(distinct([for m in var.masters : m.name])) == length(var.masters)
    error_message = "masters must have at least one entry and unique names."
  }
  validation {
    condition     = alltrue([for m in var.masters : can(regex("^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$", m.mac_address))])
    error_message = "Each masters[].mac_address must be a valid MAC address."
  }
}

variable "workers" {
  type = list(object({
    name        = string
    mac_address = string
  }))
  default = [
    { name = "worker01", mac_address = "00:50:56:ad:22:b0" }
  ]
  validation {
    condition     = length(var.workers) > 0 && length(distinct([for w in var.workers : w.name])) == length(var.workers)
    error_message = "workers must have at least one entry and unique names."
  }
  validation {
    condition     = alltrue([for w in var.workers : can(regex("^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$", w.mac_address))])
    error_message = "Each workers[].mac_address must be a valid MAC address."
  }
}

data "vsphere_datacenter" "dc" {
  name = var.datacenter
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.template_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

locals {
  master_map = { for m in var.masters : m.name => m }
  worker_map = { for w in var.workers : w.name => w }
  vm_folder_name = trimspace(var.vm_folder)
  vm_folder_enabled = local.vm_folder_name != ""

  common_extra_config = {
    "disk.EnableUUID"    = "TRUE"
    "stealclock.enable"  = "TRUE"
  }
}

resource "vsphere_virtual_machine" "bootstrap" {
  name             = var.bootstrap_name
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = local.vm_folder_enabled ? local.vm_folder_name : null

  num_cpus = var.bootstrap_cpu
  memory   = var.bootstrap_memory_mb
  guest_id = data.vsphere_virtual_machine.template.guest_id

  firmware         = data.vsphere_virtual_machine.template.firmware
  efi_secure_boot_enabled = false

  scsi_type = data.vsphere_virtual_machine.template.scsi_type

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
    use_static_mac = true
    mac_address    = var.bootstrap_mac_address
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks[0].size
    thin_provisioned = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }

  extra_config = merge(local.common_extra_config, {
    "guestinfo.ignition.config.data"          = trimspace(file(var.bootstrap_ignition_b64_file))
    "guestinfo.ignition.config.data.encoding" = "base64"
  })
}

resource "time_sleep" "wait_after_bootstrap" {
  depends_on      = [vsphere_virtual_machine.bootstrap]
  create_duration = "${var.bootstrap_to_nodes_delay_seconds}s"
}

resource "vsphere_virtual_machine" "haproxy" {
  count            = var.haproxy_enabled ? 1 : 0
  name             = var.haproxy_name
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = local.vm_folder_enabled ? local.vm_folder_name : null

  num_cpus = var.haproxy_cpu
  memory   = var.haproxy_memory_mb
  guest_id = data.vsphere_virtual_machine.template.guest_id

  firmware                = data.vsphere_virtual_machine.template.firmware
  efi_secure_boot_enabled = false

  scsi_type = data.vsphere_virtual_machine.template.scsi_type

  network_interface {
    network_id     = data.vsphere_network.network.id
    adapter_type   = data.vsphere_virtual_machine.template.network_interface_types[0]
    use_static_mac = true
    mac_address    = var.haproxy_mac_address
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks[0].size
    thin_provisioned = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }

  extra_config = local.common_extra_config
}

resource "vsphere_virtual_machine" "masters" {
  depends_on       = [time_sleep.wait_after_bootstrap]
  for_each         = local.master_map
  name             = each.value.name
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = local.vm_folder_enabled ? local.vm_folder_name : null

  num_cpus = var.master_cpu
  memory   = var.master_memory_mb
  guest_id = data.vsphere_virtual_machine.template.guest_id

  firmware         = data.vsphere_virtual_machine.template.firmware
  efi_secure_boot_enabled = false

  scsi_type = data.vsphere_virtual_machine.template.scsi_type

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
    use_static_mac = true
    mac_address    = each.value.mac_address
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks[0].size
    thin_provisioned = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }

  extra_config = merge(local.common_extra_config, {
    "guestinfo.ignition.config.data"          = trimspace(file(var.master_ignition_b64_file))
    "guestinfo.ignition.config.data.encoding" = "base64"
  })
}

resource "vsphere_virtual_machine" "workers" {
  depends_on       = [time_sleep.wait_after_bootstrap]
  for_each         = local.worker_map
  name             = each.value.name
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = local.vm_folder_enabled ? local.vm_folder_name : null

  num_cpus = var.worker_cpu
  memory   = var.worker_memory_mb
  guest_id = data.vsphere_virtual_machine.template.guest_id

  firmware         = data.vsphere_virtual_machine.template.firmware
  efi_secure_boot_enabled = false

  scsi_type = data.vsphere_virtual_machine.template.scsi_type

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
    use_static_mac = true
    mac_address    = each.value.mac_address
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks[0].size
    thin_provisioned = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }

  extra_config = merge(local.common_extra_config, {
    "guestinfo.ignition.config.data"          = trimspace(file(var.worker_ignition_b64_file))
    "guestinfo.ignition.config.data.encoding" = "base64"
  })
}

output "bootstrap_vm_name" {
  value = vsphere_virtual_machine.bootstrap.name
}

output "master_vm_names" {
  value = keys(vsphere_virtual_machine.masters)
}

output "worker_vm_names" {
  value = keys(vsphere_virtual_machine.workers)
}

output "haproxy_vm_name" {
  value = var.haproxy_enabled ? vsphere_virtual_machine.haproxy[0].name : null
}
