---
- name: Configure DNS
  hosts: dns
  become: true
  vars_files:
    - ../group_vars/all/core.yml
    - ../group_vars/all/vcenter.yml
    - ../group_vars/all/okd.yml
  tags: [core_infra, dns]
  roles:
    - { role: sub_manager, when: platform_roles.sub_manager_enabled | bool, tags: [platform, pre_vcenter, sub_manager] }
    - { role: install_initial_packages, when: platform_roles.install_initial_packages_enabled | bool, tags: [platform, pre_vcenter, initial_packages] }
    - { role: firewall_conf, firewall_profile: dns, tags: [core_infra, dns, firewall] }
    - { role: dns_conf, tags: [core_infra, dns] }

- name: Baseline Linux platform roles
  hosts: rhel
  become: true
  tags: [core_infra, baseline, platform]
  vars_files:
    - ../vault_linux_sub_manager.yml
    - ../vault_ad_connect_user.yml
  roles:
    - { role: sub_manager, when: platform_roles.sub_manager_enabled | bool, tags: [platform, pre_vcenter, sub_manager] }
    - { role: install_initial_packages, when: platform_roles.install_initial_packages_enabled | bool, tags: [platform, pre_vcenter, initial_packages] }
    - { role: ansible_user, when: platform_roles.ansible_user_enabled | bool, tags: [core_infra, baseline, ansible_user] }
    - { role: ntp_conf, when: platform_roles.ntp_conf_enabled | bool, tags: [core_infra, baseline, ntp] }
    - { role: sssd_conf, when: (platform_roles.ad_join_enabled | bool) or (platform_roles.sssd_conf_enabled | bool), tags: [core_infra, baseline, sssd] }

- name: Configure Ansible control host firewall
  hosts: ansible
  become: true
  tags: [core_infra, ansible, firewall]
  roles:
    - { role: firewall_conf, firewall_profile: ansible, tags: [core_infra, ansible, firewall] }

- name: Configure HAProxy
  hosts: haproxy
  become: true
  tags: [core_infra, haproxy]
  roles:
    - { role: firewall_conf, firewall_profile: haproxy, tags: [core_infra, haproxy, firewall] }
    - { role: haproxy_conf, tags: [core_infra, haproxy] }

- name: Configure NFS storage server (optional)
  hosts: nfs
  become: true
  tags: [core_infra, nfs]
  roles:
    - { role: firewall_conf, firewall_profile: nfs, tags: [core_infra, nfs, firewall] }
    - { role: lvm_create, when: (platform_roles.nfs_lvm_enabled | default(false)) | bool, tags: [core_infra, nfs, lvm] }
    - { role: nfs_conf, when: (platform_roles.nfs_conf_enabled | default(false)) | bool, tags: [core_infra, nfs] }
